package ast.expresiones;

public enum KindE {
  SUMA,MUL,NUM, RESTA, DIV, MOD, AND, OR, MENIG,
  MAYIG, MEN, MAY, IGU, DESIG, PUNTO, TRUE, FALSE,
  CHAR, REF, NEG, MENOS, LISTA, LLAMADA, NULL, DESIGNADOR, NEW, READ   
}
