
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 23 20:26:26 CET 2022
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CONST = 13;
  public static final int CHAR = 3;
  public static final int CCIERRE = 32;
  public static final int PCIERRE = 30;
  public static final int LCIERRE = 34;
  public static final int LAP = 33;
  public static final int CASE = 16;
  public static final int RESTA = 25;
  public static final int CAP = 31;
  public static final int CONTINUE = 12;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 46;
  public static final int REF = 43;
  public static final int FOR = 7;
  public static final int DELETE = 22;
  public static final int AND = 27;
  public static final int IGUAL = 39;
  public static final int CARACTER = 53;
  public static final int OR = 28;
  public static final int BOOL = 4;
  public static final int CLASS = 5;
  public static final int DIV = 26;
  public static final int SUMA = 23;
  public static final int TYPEDEF = 48;
  public static final int IF = 9;
  public static final int THIS = 21;
  public static final int EOF = 0;
  public static final int ASIG = 42;
  public static final int AST = 24;
  public static final int RETURN = 18;
  public static final int TRUE = 19;
  public static final int DESIG = 40;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int NULL = 51;
  public static final int MENOR = 38;
  public static final int MOD = 44;
  public static final int BREAK = 11;
  public static final int VOID = 14;
  public static final int SWITCH = 10;
  public static final int MAYOR = 36;
  public static final int ENT = 52;
  public static final int PAP = 29;
  public static final int NEG = 41;
  public static final int ELSE = 49;
  public static final int PUNTO = 45;
  public static final int MAYORIG = 35;
  public static final int IDEN = 54;
  public static final int WHILE = 8;
  public static final int DEFAULT = 15;
  public static final int MENORIG = 37;
  public static final int POINTER = 50;
  public static final int FALSE = 20;
  public static final int STRUCT = 6;
}

