
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 16 16:36:53 CET 2022
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CONST = 13;
  public static final int CHAR = 3;
  public static final int CCIERRE = 35;
  public static final int PCIERRE = 33;
  public static final int LCIERRE = 37;
  public static final int LAP = 36;
  public static final int CASE = 16;
  public static final int RESTA = 28;
  public static final int CAP = 34;
  public static final int CONTINUE = 12;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 49;
  public static final int REF = 46;
  public static final int FOR = 7;
  public static final int DELETE = 22;
  public static final int AND = 30;
  public static final int IGUAL = 42;
  public static final int CARACTER = 51;
  public static final int OR = 31;
  public static final int BOOL = 4;
  public static final int CLASS = 5;
  public static final int DIV = 29;
  public static final int SUMA = 26;
  public static final int IF = 9;
  public static final int THIS = 21;
  public static final int EOF = 0;
  public static final int ASIG = 45;
  public static final int AST = 27;
  public static final int RETURN = 18;
  public static final int TRUE = 19;
  public static final int DESIG = 43;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int COMA = 50;
  public static final int MENOR = 41;
  public static final int MOD = 47;
  public static final int BREAK = 11;
  public static final int VOID = 14;
  public static final int SWITCH = 10;
  public static final int MAYOR = 39;
  public static final int ENT = 25;
  public static final int PAP = 32;
  public static final int NEG = 44;
  public static final int PUNTO = 48;
  public static final int MAYORIG = 38;
  public static final int IDEN = 24;
  public static final int WHILE = 8;
  public static final int DEFAULT = 15;
  public static final int MENORIG = 40;
  public static final int BUILD = 23;
  public static final int FALSE = 20;
  public static final int STRUCT = 6;
  public static final int TYPEDEF = -9;
public static final int ELSE = -10;
}

